### ISSUE TITLE
Edit draft not displayed if moderation is disabled.

### ISSUE THREAD

**Issue by svenl77** [BuddyForms/BuddyForms-Moderation#5]
There was a situation where a user has deactivated the moderation but the posts get created with status edit draft.

Also the edit draft is only visible if moderation is enabled. Therefore the posts have been hidden to the user.

We need to make sure the default post status is used if moderation is deactivated.

**Comment by laneylaneylane** [comment]
Following... I am the user having the issue. Thank you Sven.
